- hosts: all
  become: true

  tasks:
    - name: install haproxy repo
      apt_repository: repo=ppa:vbernat/haproxy-1.7

    - name: update apt cache
      apt: update_cache=yes cache_valid_time=3600

    - name: install haproxy
      apt: name=haproxy state=present

    - name: update haproxy config
      template: src=templates/haproxy.cfg dest=/etc/haproxy/haproxy.cfg backup=yes
      notify:
        - reload haproxy
        - restart rsyslog

  handlers:
    - name: reload haproxy
      systemd: name=haproxy state=reloaded

    - name: restart rsyslog
      systemd: name=rsyslog state=restarted