- hosts: all
  become: true

  tasks:
    - name: update apt cache
      apt: update_cache=yes cache_valid_time=3600

    - name: install haproxy
      apt: name=haproxy state=present

    - name: update haproxy config
      template: src=templates/haproxy.cfg dest=/etc/haproxy/haproxy.cfg backup=yes
      notify:
        - restart haproxy

  handlers:
    - name: restart haproxy
      service: name=haproxy state=restarted